server:
  port: 8080

spring:
  application:
    name: "devices"

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devicedb
    username: "YOUR_DB_USERNAME"
    password: "YOUR_DB_PASSWORD"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always
      platform: mysql

  app:
    jwtSecret: "YOUR_JWT_SECRET"
    jwtExpirationMs: "YOUR_JWT_EXPIRATION_IN_MS"

#For Spring Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#

# for spring cloud binder kafka
  cloud:
    function:
      definition: deviceUpdateEventSupplier;deviceCreateEventSupplier
    stream:
      bindings:
        deviceCreateEventSupplier-out-0:
          destination: device-create
          content-type: application/json
        deviceUpdateEventSupplier-out-0:
          destination: admin-update
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
#
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.thomas.device: DEBUG

info:
  app:
    name: "device"
    description: "Device Application"
    version: "1.0.0"
